### ISSUE TITLE
CF in kubernetes

### ISSUE THREAD

**Issue by zreigz** [hpcloud/fissile#204]
Hello
We as a Fujitsu are very interested to run CF in Kubernetes. I am not a CF expert. I have experience in k8s.
I've seen a presentation how to do it but I can not find and documentation or examples which could help me. Can someone drive me ho to do it ? Any help is appreciated.
I assume I have to convert CF components to Docker images and create pods. So If someone have some scripts or k8s deployment file it would be very helpful. 
Please excuse my lack of knowledge because I've already started picking up knowledge about CF and fissile

**Comment by viovanov** [comment]
Hi @zreigz, a good place to start would be the [cf-solo](https://github.com/hpcloud/cf-solo) project that has an example on how to create a docker image that has all of CF in it.
Then, you could use the new `fissile kube` command (merged today) to generate kube configs.

It would be great If you could join the CF #fissile slack. Our team would love to help, and in the process of getting you going we could write a better "getting started" tutorial.

**Comment by zreigz** [comment]
Thanks a lot for replay. I've just compiled fissile from master branch and I have this error:
```
$ ./fissile kube
unknown command "kube" for "fissile"
```

**Comment by aarondl** [comment]
Hey @zreigz, please join the Cloud Foundry Slack instance (invite page here: https://slack.cloudfoundry.org/) and go to the #fissile channel to continue this discussion. Let's not have long conversations using Github issues as the medium. We'll convert any problems you find into issues and it will be much easier to help you there. Thanks!
